#!/bin/bash

DST="$HOME/.local/bin"

if [ ! -d $DST ]; then
	mkdir $DST
fi

for FILE in *
do
	TRG="$(pwd)/$FILE"
	#echo "$TRG" 

	# Remove existing
	DEL="$DST/$FILE"
	if [ -f $DEL ]; then
		rm $DEL
	fi

	# Create symbolic link
	#echo "ln -s $TRG $DST" 
	ln -s $TRG $DST
done
