#!/bin/bash

export PATH="$PATH:$HOME/development/flutter/bin"

#export PATH="$PATH:/var/data/python/bin"
#export PATH="$PATH:$JAVA_HOME/bin"
#export PATH="/usr/lib/postgresql/12/bin:$PATH"
# export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
#export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export ANDROID_SDK="$HOME/Android/sdk"
export PATH="$PATH:$ANDROID_SDK/platform-tools"
export PATH="$PATH:$ANDROID_SDK/emulator"
export PATH="$PATH:$ANDROID_SDK/tools"

wmctrl -s 1
google-chrome
