#!/bin/bash
S_N=2

wmctrl -s $((S_N++))
code ~/Projects/Python/template-backend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/NodeJS/template-frontend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/Docker/template-docker
sleep 1


wmctrl -s 1
