#!/bin/bash

wmctrl -s 2
code ~/Projects/Python/LekNaServer
sleep 3

wmctrl -s 3
code ~/Projects/NodeJS/LekNaFrontend
sleep 3

wmctrl -s 4
code ~/Projects/Docker/LekNaDocker
sleep 3

wmctrl -s 5
code ~/Projects/Python/PngToSvg
sleep 3

wmctrl -s 6
code ~/Projects/Python/xlsx2lang
sleep 3


wmctrl -s 1
