#!/bin/bash
S_N=2

wmctrl -s $((S_N++))
code ~/Projects/Python/casinos-backend
code ~/Projects/Python/plotka-backend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/NodeJS/casinos-frontend
code ~/Projects/NodeJS/plotka-frontend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/Docker/casinos-docker
code ~/Projects/Docker/plotka-docker
sleep 1


wmctrl -s 1
