#!/bin/bash
S_N=2

wmctrl -s $((S_N++))
code ~/Projects/Python/casino-backend
code ~/Projects/Python/plotka-backend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/NodeJS/casino-frontend
code ~/Projects/NodeJS/plotka-frontend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/Docker/casino-docker
code ~/Projects/Docker/plotka-docker
sleep 1


wmctrl -s 1
