#!/bin/bash

S_N=2

wmctrl -s $((S_N++))
code ~/Projects/Python/LekNaServer
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/Flutter/lek_na_flutter
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/NodeJS/LekNaFrontend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/Docker/LekNaDocker
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/Python/PngToSvg
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/Python/xlsx2lang
sleep 3


wmctrl -s 1
