#!/bin/bash

wmctrl -s 1
code ~/Projects/Docker/ldek-docker/backend
sleep 3

wmctrl -s 2
code ~/Projects/SYNC/NodeJS/ldek/LekNaFrontend
sleep 3

wmctrl -s 3
code ~/Projects/Docker/ldek-docker
sleep 3

wmctrl -s 4
code ~/Projects/Python/potrace_icon
sleep 3

wmctrl -s 5
code ~/Projects/SYNC/Python/xlsx2lang
sleep 3


wmctrl -s 1
