#!/usr/bin/env python

import json
import re
import logging
from enum import Enum

logging.basicConfig(level=logging.DEBUG)


class Changes(Enum):
    DOMAIN = "domain"


data = {
    Changes.DOMAIN: "sinproject.pl",
}


filename = "replace-table.json"


class App:
    def __init__(self) -> None:
        self._read_replace_table()

    def _read_replace_table(self):
        with open(filename) as f:
            self.replace_table = json.load(f)

    def start(self):
        for d in self.replace_table:
            logging.debug(f'FILE: {d["file"]}')
            with open(d["file"]) as f:
                text = f.read()

            pattern = d["pattern"]
            regex = pattern.replace("{}", d["regex"])

            word = data[Changes(d["key"])]
            replace_with = pattern.format(word)

            text = re.sub(regex, replace_with, text)

            # Save changes into file
            # with open(d["file"], 'w') as f:
            #     f.write(text)
            # print(text)


if __name__ == "__main__":
    domain = "test.happy.ovh"
    # domain_input = input(f"Domena ({domain}): ")
    # if domain_input != "":
    #     domain = domain_input

    for key in Changes:
        logging.info(f'{key.value.upper()}: {data[key]}')

    app = App()
    app.start()
