#!/bin/bash

NAME="sinproject"
PROJECTS_DIR="$HOME/Projects/Combined"

PARENT_DIR="$PROJECTS_DIR/$NAME"

if [ ! -d $PARENT_DIR ]
then
	echo "No $PARENT_DIR exists!"
#	exit
fi

TYPES=""
TYPES+="backend "
TYPES+="frontend "
TYPES+="docker "

S_N=2
for TYPE in $TYPES
do
	echo $PARENT_DIR/$NAME-$TYPE

	((S_N++))
done


exit 

wmctrl -s $((S_N++))
code ~/Projects/Python/casinos-backend
code ~/Projects/Python/plotka-backend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/NodeJS/casinos-frontend
code ~/Projects/NodeJS/plotka-frontend
sleep 3

wmctrl -s $((S_N++))
code ~/Projects/Docker/casinos-docker
code ~/Projects/Docker/plotka-docker
sleep 1


wmctrl -s 1
